name: sushail

on:
  push:
    branches:
      - main  # ou la branche de ton choix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        sudo apt-get update
        sudo apt-get install git

    - name: Exécuter le script de déploiement
      run: |
        chmod +x deploy.sh
        ./deploy.sh
        
